#Absoluter Pfad zu der Konfigurationsdatei
# globale Variablen
cardTitleConf = "Meine erste Smarty-Seite von der conf-Seite"
# Kundenvariablen
[Kunden]
seitenTitel = "Kundeninfo"
nocheintitle = "Geht auch!"

